In [3]:
import numpy as np

In [4]:
a=np.array([[1,2,3,4,5]])

In [5]:
print(a)

[[1 2 3 4 5]]


In [6]:
print(a.ndim)

2


In [4]:
a=np.array([[1,2,3,4,5],[10,20,30,40,50]])

In [5]:
print(a)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [6]:
a=np.array([[1,2,3,4,5],[10,20,30,40,50]],dtype="int32")

In [7]:
a.itemsize

4

In [8]:
a.shape

(2, 5)

In [9]:
a.size

10

In [10]:
a[0,2]

3

In [11]:
a[1,4]

50

In [6]:
a[0,:]

array([1, 2, 3, 4, 5])

In [7]:
a[0,:2]

array([1, 2])

In [8]:
a[:,2]

array([3])

In [9]:
a[:2,2:]

array([[3, 4, 5]])

In [10]:
a[0,2]

3

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((4,3),dtype="int32")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
np.ones((4,3),dtype="float32")

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [14]:
x=np.ones((4,3))

In [15]:
x.dtype

dtype('float64')

In [16]:
x=np.ones((4,3),dtype="int64")

In [17]:
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [18]:
np.full((3,4),50)

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [19]:
np.full_like(x,5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=int64)

In [20]:
np.random.rand(3,3)

array([[0.42714328, 0.80534705, 0.10227028],
       [0.04572173, 0.90420758, 0.63628097],
       [0.27556544, 0.46446819, 0.99382377]])

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
a=np.array([1,2,3,4,5])

In [24]:
b=np.array([10,20,30,40,50])

In [25]:
a+10

array([11, 12, 13, 14, 15])

In [26]:
a-10

array([-9, -8, -7, -6, -5])

In [27]:
b+20

array([30, 40, 50, 60, 70])

In [28]:
b-30

array([-20, -10,   0,  10,  20])

In [29]:
a*2

array([ 2,  4,  6,  8, 10])

In [30]:
b*4

array([ 40,  80, 120, 160, 200])

In [31]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [32]:
b/4

array([ 2.5,  5. ,  7.5, 10. , 12.5])

In [33]:
a**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [34]:
b**2

array([ 100,  400,  900, 1600, 2500], dtype=int32)

In [35]:
a+b

array([11, 22, 33, 44, 55])

In [36]:
a-b

array([ -9, -18, -27, -36, -45])

In [39]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [40]:
np.cos(b)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [41]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [42]:
np.matmul(a,b)

550

In [43]:
n=np.arange(10)

In [44]:
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
n.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
n.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [47]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [48]:
np.arange(4,20,3)

array([ 4,  7, 10, 13, 16, 19])

In [50]:
a=np.array([[1,2,3,4,5],[10,20,30,40,50]])

In [51]:
a.flatten()

array([ 1,  2,  3,  4,  5, 10, 20, 30, 40, 50])

In [54]:
a=np.array([1,2,3,4,5],dtype="float64")

In [55]:
np.reciprocal(a)

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [57]:
np.random.randint(5,10,size=(3,3))

array([[8, 7, 8],
       [5, 5, 6],
       [6, 8, 5]])

In [58]:
a=np.array([5,15,20])

In [59]:
b=np.array([2,5,9])

In [60]:
np.mod(a,b)

array([1, 0, 2], dtype=int32)